backend/.eslintrc.js
backend/.gitignore
backend/.prettierrc
backend/README.md
backend/nest-cli.json
backend/package-lock.json
backend/package.json
backend/src/app.controller.spec.ts
backend/src/app.controller.ts
backend/src/app.module.ts
backend/src/app.service.ts
backend/src/main.ts
backend/test/app.e2e-spec.ts
backend/test/jest-e2e.json
backend/tsconfig.build.json
backend/tsconfig.json

NestJS 프로젝트 초기 설정

---

.github/workflows/firebase-deploy.yml
.github/workflows/ktlint.yml
android/app/build.gradle

- Firebase Deploy: 배포하면서 릴리즈 노트도 추가할 수 있게끔 변경하였습니다. 추가로 오류도 수정했습니다.
- Ktlint: Job 이름을 변경하였습니다.

워크플로우 출시 노트 추가, Job 이름 변경

---

android/app/src/main/java/app/priceguard/data/network/UserAPI.kt
android/app/src/main/java/app/priceguard/ui/login/LoginActivity.kt

URL 수정 및 로그인 다이얼로그 로딩 버튼 버그 수정

---

android/app/src/main/res/layout-land/activity_intro.xml
android/app/src/main/res/layout/activity_intro.xml

https://github.com/boostcampwm2023/and09-PriceGuard/assets/83055885/3fa6f883-1b92-4067-855f-5ff975141755

Intro Activity 가로 화면 대응 추가

---

.github/workflows/backend-deploy.yml
backend/Dockerfile
backend/package-lock.json
backend/package.json
backend/src/app.module.ts
backend/src/configs/winston.config.ts
backend/src/exceptions/exception.fillter.ts

Resolves #83 
Winston과 NestJS를 연동해서 콘솔에 로그를 출력하고 로그 파일을 생성할 수 있게 하였습니다.

서버 로그 파일 생성

---

android/app/src/main/java/app/priceguard/ui/login/LoginActivity.kt
android/app/src/main/java/app/priceguard/ui/login/LoginViewModel.kt
android/app/src/main/java/app/priceguard/ui/signup/SignupActivity.kt
android/app/src/main/java/app/priceguard/ui/signup/SignupViewModel.kt
android/app/src/main/java/app/priceguard/ui/util/drawable/ProgressIndicator.kt

Circular Progress Indicator 통일

---

android/app/src/main/java/app/priceguard/ui/signup/SignupActivity.kt

Lifecycle 유틸 함수 사용

---

android/app/build.gradle.kts
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/app/priceguard/data/dto/ProductInfo.kt
android/app/src/main/java/app/priceguard/ui/main/additem/AddItemActivity.kt
android/app/src/main/java/app/priceguard/ui/main/additem/ConfirmItemLinkFragment.kt
android/app/src/main/java/app/priceguard/ui/main/additem/ConfirmItemLinkViewModel.kt
android/app/src/main/java/app/priceguard/ui/main/additem/RegisterItemLinkFragment.kt
android/app/src/main/java/app/priceguard/ui/main/additem/SetTargetPriceFragment.kt
android/app/src/main/res/drawable/bg_round_corner.xml
android/app/src/main/res/drawable/ic_11st_logo.xml
android/app/src/main/res/drawable/ic_close.xml
android/app/src/main/res/drawable/ic_next.xml
android/app/src/main/res/layout/activity_add_item.xml
android/app/src/main/res/layout/fragment_confirm_item_link.xml
android/app/src/main/res/layout/fragment_register_item_link.xml
android/app/src/main/res/layout/fragment_set_target_price.xml
android/app/src/main/res/navigation/nav_graph.xml
android/app/src/main/res/values/strings.xml

- Resolves #2 
- Resolves #27 
https://github.com/boostcampwm2023/and09-PriceGuard/assets/83055885/663a2cee-7e7d-4a4c-994b-17cf30f86ce6

상품 추가 화면 구현

---

backend/src/entities/token.entity.ts

Token 엔터티 이름 지정

---

backend/package-lock.json
backend/package.json
backend/src/configs/typeorm.config.ts
backend/src/constants.ts
backend/src/dto/product.details.dto.ts
backend/src/dto/product.swagger.dto.ts
backend/src/product/product.controller.ts
backend/src/product/product.service.ts
backend/src/utils/openapi.11st.ts

상품 URL 검증 API 구현

---

android/app/src/main/java/app/priceguard/data/dto/ProductAddRequest.kt
android/app/src/main/java/app/priceguard/data/dto/ProductDTO.kt
android/app/src/main/java/app/priceguard/data/dto/ProductListResponse.kt
android/app/src/main/java/app/priceguard/data/dto/ProductResponse.kt
android/app/src/main/java/app/priceguard/data/dto/ProductVerifyRequest.kt
android/app/src/main/java/app/priceguard/data/network/ProductAPI.kt
android/app/src/main/java/app/priceguard/data/network/RequestInterceptor.kt
android/app/src/main/java/app/priceguard/data/repository/ProductRepository.kt
android/app/src/main/java/app/priceguard/data/repository/ProductRepositoryImpl.kt
android/app/src/main/java/app/priceguard/di/NetworkModule.kt
android/app/src/main/java/app/priceguard/di/ProductRepositoryModule.kt
android/app/src/main/java/app/priceguard/ui/main/additem/AddItemActivity.kt
android/app/src/main/java/app/priceguard/ui/main/additem/RegisterItemLinkFragment.kt

[목록 화면, 상품 추가 화면]  Repository 추가 및 기본 세팅

---

backend/src/auth/auth.service.ts
backend/src/exceptions/http.exception.filter.ts
backend/src/product/product.service.ts

피드백 반영 및 오류 수정

---

backend/src/dto/product.swagger.dto.ts
backend/src/product/product.controller.ts
backend/src/product/product.service.ts

Resolves #42 
- 상품 코드를 통해 상품 ID를 알아내는 과정에서 상품이 없으면 에러 응답
- 사용자 ID와 상품 ID를 이용하여 현재 추적 중인 상품 테이블에서 해당 상품 삭제
- 삭제할 상품이 추적 테이블에 없으면 에러 응답

추적 상품 삭제 API 구현

---

android/app/build.gradle.kts
android/build.gradle.kts

Firebase Crashlytics, Performance Monitoring SDK 추가

---

backend/src/dto/product.swagger.dto.ts
backend/src/product/product.controller.ts
backend/src/product/product.service.ts

목표 가격 수정 API 구현

---

backend/src/constants.ts
backend/src/product/product.service.ts
backend/src/product/trackingProduct.repository.ts

Resolves #123 
- tracking_product 테이블에서 상품을 추적 중인 유저수가 많은 순서로 정렬하여 목록 반환하는 쿼리 생성
- 환경 변수로 추적 상품 인기 순위의 최대 범위를 조절하여 개발 환경과 배포 환경에서 따로 관리할 수 있도록 구현
- 최대 범위를 넘어가는 상품의 인기 순위는 `-1`로 지정

제품 상세정보 현재 트래킹 순위 반영

---

backend/src/app.controller.spec.ts
backend/src/app.controller.ts
backend/src/app.module.ts
backend/src/app.service.ts

Ping API 구현

---

android/app/build.gradle.kts
android/app/src/main/java/app/priceguard/ui/detail/DetailActivity.kt
android/app/src/main/java/app/priceguard/ui/detail/ProductDetailViewModel.kt
android/app/src/main/java/app/priceguard/ui/home/list/ProductListFragment.kt
android/app/src/main/java/app/priceguard/ui/home/list/ProductListViewModel.kt
android/app/src/main/java/app/priceguard/ui/home/recommend/RecommendedProductFragment.kt
android/app/src/main/java/app/priceguard/ui/home/recommend/RecommendedProductViewModel.kt
android/app/src/main/res/layout/activity_detail.xml
android/app/src/main/res/layout/fragment_product_list.xml
android/app/src/main/res/layout/fragment_recommended_product.xml
android/app/src/main/res/menu/list_top_app_bar_menu.xml

- Resolves #12
- Resolves #50
- Resolves #53
트래킹하는 상품 목록 & 추천 상품 목록의 새로고침은 기존의 Toolbar Refresh 버튼에서 위로 당겨서 새로고침으로 변경
https://github.com/boostcampwm2023/and09-PriceGuard/assets/27392567/68bc7ee7-95cf-401b-9c88-5bf9a67d7a70

새로고침이 가능해야한 페이지에 위로 당겨서 새로고침 구현

---

android/app/src/main/java/app/priceguard/data/dto/PricePatchRequest.kt
android/app/src/main/java/app/priceguard/data/dto/PricePatchResponse.kt
android/app/src/main/java/app/priceguard/data/dto/ProductDTO.kt
android/app/src/main/java/app/priceguard/data/network/ProductAPI.kt
android/app/src/main/java/app/priceguard/data/repository/ProductRepository.kt
android/app/src/main/java/app/priceguard/data/repository/ProductRepositoryImpl.kt
android/app/src/main/java/app/priceguard/ui/additem/AddItemActivity.kt
android/app/src/main/java/app/priceguard/ui/additem/confirm/ConfirmItemLinkFragment.kt
android/app/src/main/java/app/priceguard/ui/additem/setprice/SetTargetPriceFragment.kt
android/app/src/main/java/app/priceguard/ui/additem/setprice/SetTargetPriceViewModel.kt
android/app/src/main/java/app/priceguard/ui/detail/DetailActivity.kt
android/app/src/main/res/layout/fragment_set_target_price.xml
android/app/src/main/res/navigation/nav_graph.xml

Resolves #48 
기존 코드 유지보수 필요해보입니다.
https://github.com/boostcampwm2023/and09-PriceGuard/assets/37584805/aa969ce6-11f0-4bdd-aaca-610a54ae30a2

목표 가격 수정 구현 및 화면 이동 적용

---

android/app/src/main/java/app/priceguard/ui/detail/DetailActivity.kt
android/app/src/main/java/app/priceguard/ui/home/list/ProductListFragment.kt
android/app/src/main/java/app/priceguard/ui/home/list/ProductListViewModel.kt
android/app/src/main/java/app/priceguard/ui/home/recommend/RecommendedProductFragment.kt
android/app/src/main/java/app/priceguard/ui/home/recommend/RecommendedProductViewModel.kt

자동 새로고침 구현

---

.gitmodules
android/.idea/gradle.xml
android/app/build.gradle.kts
android/settings.gradle

차트 라이브러리 서브모듈 추가

---

backend/src/constants.ts
backend/src/dto/product.swagger.dto.ts
backend/src/product/product.controller.ts
backend/src/schema/product.schema.ts

MongoDB Schema 및 Swagger 수정

---

android/app/src/main/java/app/priceguard/data/dto/PriceDataDTO.kt
android/app/src/main/java/app/priceguard/data/dto/ProductDTO.kt
android/app/src/main/java/app/priceguard/data/dto/ProductResponse.kt
android/app/src/main/java/app/priceguard/data/dto/RecommendProductDTO.kt
android/app/src/main/java/app/priceguard/data/graph/GraphDataConverter.kt
android/app/src/main/java/app/priceguard/data/graph/ProductChartData.kt
android/app/src/main/java/app/priceguard/data/graph/ProductChartDataset.kt
android/app/src/main/java/app/priceguard/data/graph/ProductChartGridLine.kt
android/app/src/main/java/app/priceguard/data/repository/ProductRepositoryImpl.kt
android/app/src/main/java/app/priceguard/di/ProductRepositoryModule.kt
android/app/src/main/java/app/priceguard/ui/detail/DetailActivity.kt
android/app/src/main/java/app/priceguard/ui/detail/ProductDetailViewModel.kt
android/app/src/main/java/app/priceguard/ui/home/ProductSummary.kt
android/app/src/main/java/app/priceguard/ui/home/ProductSummaryAdapter.kt
android/app/src/main/java/app/priceguard/ui/home/list/ProductListViewModel.kt
android/app/src/main/java/app/priceguard/ui/home/recommend/RecommendedProductViewModel.kt
android/app/src/main/res/layout/activity_detail.xml
android/app/src/main/res/layout/item_product_summary.xml
android/app/src/main/res/values/themes.xml

- Resolves #24 
추가로 작업해야할 사항
<p float="left">
</p>

[그래프] 그래프 하위 모듈 추가 후 적용

---

.github/workflows/firebase-deploy.yml

서브모듈까지 레포를 받아오게끔 수정

---

android/app/src/main/java/app/priceguard/ui/detail/DetailActivity.kt

역대최저가 가로선 삭제

---

backend/src/constants.ts
backend/src/product/product.service.ts

[Data 옵션](https://firebase.google.com/docs/cloud-messaging/send-message?hl=ko&authuser=0#customize-messages-across-platforms)
[Channel ID 옵션](https://firebase.google.com/docs/reference/admin/node/firebase-admin.messaging.androidnotification.md?hl=ko#androidnotificationchannelid)

FCM 메시지 옵션 추가

---

backend/src/cron/cron.service.ts
backend/src/product/product.controller.ts
backend/src/product/product.module.ts
backend/src/product/product.service.ts

* ProductService에 있는 Cron 로직을 CronService 클래스로 분리
* 기능이 복합적으로 존재하는 코드 중 몇몇 기능을 함수로 분리
* MongoDB 연결 테스트 API 삭제

Cron Job을 별도의 클래스로 분리

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/app/priceguard/ui/additem/link/LinkHelperWebViewActivity.kt
android/app/src/main/java/app/priceguard/ui/additem/link/RegisterItemLinkFragment.kt
android/app/src/main/res/layout/activity_link_helper_web_view.xml
android/app/src/main/res/values/strings.xml

https://github.com/boostcampwm2023/and09-PriceGuard/assets/83055885/55c9722c-7371-4acc-ab46-3f28d824cb14

상품 링크 등록 도움말 웹뷰 보여주는 액티비티 추가

---

backend/src/product/product.service.ts

- 트래킹 상품을 삭제하는 과정에서 인기 상품 캐시에 없으면 '상품을 찾을 수 없습니다' 에러를 반환하여 삭제되지 않는 오류를 수정하였습니다.
- 상품의 현재 가격과 최저가를 구할 때, redis를 적용하기 전에는 local cache에 상품 정보가 담겨있어 cache를 통해 조회하도록 하였습니다.
- 하지만 지금은 cache를 redis로 변경하였기 때문에 조회 시 network I/O가 발생합니다.
- 따라서 Mongo로부터 조회한 전체 가격 데이터를 활용하여 현재 가격과 최저가를 구하도록 변경하였습니다.

트래킹 상품 삭제 버그 수정, 상품 현재 가격 정보 조회 방식 변경

---

android/app/src/main/java/app/priceguard/ui/home/ProductSummaryAdapter.kt
android/app/src/main/java/app/priceguard/ui/home/list/ProductListFragment.kt
android/app/src/main/java/app/priceguard/ui/home/list/ProductListViewModel.kt
android/app/src/main/java/app/priceguard/ui/home/recommend/RecommendedProductFragment.kt

홈화면 RecyclerView 토글 오류 수정

---

android/app/src/main/res/layout/activity_detail.xml

상품 상세 페이지가 로딩될때 누를 수 있는 모든 버튼을 비활성화

---

android/app/src/main/res/layout/activity_detail.xml

Resolves #197 
https://stackoverflow.com/questions/44407092/saving-scroll-state-of-nestedscrollview
해당 글 참고.

[개선] 상세화면 스크롤 초기화 버그 해결

---

android/app/build.gradle.kts

MaterialChart 라이브러리 최신 버전으로 업데이트

---

backend/src/auth/auth.service.ts
backend/src/auth/jwt/jwt.service.ts
backend/src/constants.ts
backend/src/product/product.service.ts

Resolves #194 
트래킹 상품 삭제 시, 인기 상품 목록을 갱신하는 과정에서 상품이 중복되던 버그를 수정하였습니다.
redis의 기능을 이용할 때, I/O가 더 적게 일어나도록 함수를 변경하였습니다.
redis에 값을 저장 할 때, 각 데이터에 적절한 TTL을 설정하여 주었습니다.

인기 상품 버그 수정, Redis TTL 설정

---

android/app/src/main/java/app/priceguard/ui/PriceGuardApp.kt

priceGuardApplication 클래스에서 버전에 따라 UiModeManger, AppCompatDelegate로 분기하는 코드 제거
다크모드 설정 else문에 시스템 테마 따라가는 설정 추가

테마 변경 후 앱 재시작 시 테마 변경이 안되는 오류 수정

---

backend/src/constants.ts

tracking product cache 최대 값 환경 변수로 관리

---

backend/src/product/product.service.ts

목표 가격 수정 시,  트래킹 cache 미반영 오류 수정

---

android/app/src/main/java/app/priceguard/ui/additem/setprice/SetTargetPriceFragment.kt
android/app/src/main/res/layout/activity_detail.xml

[상품 추가 화면] 숫자는 보정되지 않도록 변경

---

android/app/src/main/java/app/priceguard/ui/additem/link/RegisterItemLinkViewModel.kt

[hotfix] 링크 입력 후 모두 지워도 버튼이 활성화 되는 버그 수정

---

android/app/src/main/java/app/priceguard/ui/home/list/ProductListFragment.kt
android/app/src/main/java/app/priceguard/ui/home/list/ProductListViewModel.kt
android/app/src/main/java/app/priceguard/ui/home/recommend/RecommendedProductFragment.kt
android/app/src/main/java/app/priceguard/ui/home/recommend/RecommendedProductViewModel.kt
android/app/src/main/java/app/priceguard/ui/util/drawable/ProgressIndicator.kt
android/app/src/main/res/layout/fragment_product_list.xml
android/app/src/main/res/layout/fragment_recommended_product.xml
android/app/src/main/res/values/strings.xml
android/app/src/main/res/values/styles.xml

https://github.com/boostcampwm2023/and09-PriceGuard/assets/37584805/8e44da77-511a-4799-9f0c-2d7bf965262b

로딩 애니메이션 추가

---

backend/src/utils/product.info.ts

- URL 검증 API를 버저닝 하는 과정에서, 버전을 비교하는 로직이 잘못되어 오류가 발생하는 내용을 수정하였습니다.

URL 검증 로직 수정

---

backend/src/constants.ts
backend/src/dto/product.swagger.dto.ts
backend/src/entities/user.entity.ts
backend/src/product/product.controller.ts
backend/src/product/product.module.ts
backend/src/product/product.service.ts
backend/src/product/trackingProduct.repository.ts

- 사용자가 기본 등급으로 tier1을 가지도록 추가하였습니다.
- 상품 등록 시, 사용자 등급에 따라 상품 등록 최대 개수를 제한하도록 하는 기능을 추가하였습니다.
- 현재는 기본 등급인 tier1만 존재합니다.

사용자 등급별 상품 개수 제한 기능 추가

---

.github/workflows/firebase-deploy.yml

v1.2.0용 워크플로우 오류 수정

---

android/app/build.gradle.kts

v1.2.0 배포용 디펜던시 오류 수정

---

.github/workflows/firebase-deploy.yml

v1.2.0 배포용 워크플로우 빌드 명령어 변경

---

android/app/build.gradle.kts
android/app/src/main/java/app/priceguard/ui/detail/DetailActivity.kt
android/build.gradle.kts
android/gradle/wrapper/gradle-wrapper.properties

라이브러리 버전 업데이트
