boostcampwm2023/and09-PriceGuard

.github/workflows/firebase-deploy.yml
.github/workflows/ktlint.yml

워크플로우 실행중 발생하는 문제들을 해결했습니다.
- Ktlint: 기존에는 변경사항에만 lint를 적용하였으나, 이미 추가된 파일에 대해서도 검사가 가능하게끔 필터 모드를 변경했습니다.
- Firebase Deploy: Base64로 인코딩된 Keystore 파일을 디코딩하면서 생기는 오류를 수정하였습니다.

워크플로우 오류 수정

---

.github/workflows/backend-deploy.yml
.github/workflows/backend-eslint-ci.yml
backend/Dockerfile

- CI: reviewdog 이용하여, PR시 backend 폴더의 eslint 검사 진행
- CD: NCP Container Registry를 이용하여 도커로 자동 배포 진행
Resolves #58

backend CI/CD 워크플로우 설정

---

android/app/build.gradle.kts
android/app/src/main/java/app/priceguard/ui/login/LoginActivity.kt
android/app/src/main/java/app/priceguard/ui/login/LoginViewModel.kt
android/app/src/main/java/app/priceguard/ui/util/lifecycle/LifecycleExtensions.kt
android/app/src/main/res/layout/activity_intro.xml
android/app/src/main/res/layout/activity_login.xml
android/app/src/main/res/values-night/themes.xml
android/app/src/main/res/values/strings.xml
android/app/src/main/res/values/styles.xml
android/app/src/main/res/values/themes.xml

Resolves #29 , resolves #33 
https://github.com/boostcampwm2023/and09-PriceGuard/assets/37584805/5cb097f3-f7e0-49e6-9e54-d8860e5fc40a

로그인 화면 생성, 이메일/비밀번호 유효성 검사, 회원가입 화면으로 전환

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/app/priceguard/ui/signup/SignupActivity.kt
android/app/src/main/java/app/priceguard/ui/signup/SignupViewModel.kt
android/app/src/main/res/drawable/ic_back.xml
android/app/src/main/res/layout/activity_signup.xml
android/app/src/main/res/values-night/themes.xml
android/app/src/main/res/values/strings.xml
android/app/src/main/res/values/styles.xml
android/app/src/main/res/values/themes.xml

Resolves #8, resolves #10, resolves #11
https://github.com/boostcampwm2023/and09-PriceGuard/assets/27392567/02c58305-c270-4a7d-a346-1f3e4d245aee

회원가입 입력 구현

---

android/app/src/main/res/drawable/ic_priceguard_original.xml
android/app/src/main/res/layout/activity_intro.xml
android/app/src/main/res/layout/activity_login.xml

상하좌우 여백 없는 벡터 리소스로 로고 변경

---

android/app/src/main/res/values/styles.xml

Circular Progress Indicator 색상을 올바른 컬러 코드로 변경

---

android/app/src/main/res/layout-land/activity_login.xml
android/app/src/main/res/layout/activity_login.xml

[로그인 화면] NestedScrollView로 가로 화면 대응

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/app/priceguard/data/dto/LoginResponse.kt
android/app/src/main/java/app/priceguard/data/dto/SignUpResponse.kt
android/app/src/main/java/app/priceguard/data/dto/SignupRequest.kt
android/app/src/main/java/app/priceguard/data/dto/SignupResponse.kt
android/app/src/main/java/app/priceguard/data/network/UserAPI.kt
android/app/src/main/java/app/priceguard/data/repository/UserRepository.kt
android/app/src/main/java/app/priceguard/data/repository/UserRepositoryImpl.kt
android/app/src/main/java/app/priceguard/ui/login/LoginActivity.kt
android/app/src/main/java/app/priceguard/ui/login/LoginViewModel.kt
android/app/src/main/java/app/priceguard/ui/signup/SignupActivity.kt
android/app/src/main/java/app/priceguard/ui/signup/SignupViewModel.kt
android/app/src/main/java/app/priceguard/ui/splash/SplashScreenActivity.kt
android/app/src/main/res/layout/activity_splash_screen.xml
android/app/src/main/res/values-v31/styles.xml

- Resolves #37
https://github.com/boostcampwm2023/and09-PriceGuard/assets/27392567/d8106037-5ba2-41df-b4a4-3460006fe0b9

SplashScreen 구현, 로그인 & 회원가입 시 토큰 저장

---

backend/src/product/product.service.ts

```
http://m.11st.co.kr/products/ma/3895994773
http://m.11st.co.kr/products/m/5056486187?prdNo=5056486187
http://m.11st.co.kr/products/ma/6174685871?&trTypeCd=MAG3&trCtgrNo=950076
http://www.11st.co.kr/products/ma/6174685871?&trTypeCd=MAG3&trCtgrNo=950076
```
위와 같이 모바일 및 `products/ma/<상품코드>` 로 된 URL은 다 유효하지 않은 URL로 처리해버리는 경우가 있어서 정규표현식을 수정하였습니다.

URL 검사 정규 표현식 수정

---

backend/src/auth/auth.controller.ts
backend/src/auth/auth.service.ts
backend/src/auth/jwt/jwt.strategy.ts
backend/src/dto/product.swagger.dto.ts
backend/src/dto/product.tracking.dto.ts
backend/src/entities/product.entity.ts
backend/src/entities/trackingProduct.entity.ts
backend/src/entities/user.entity.ts
backend/src/exceptions/http.exception.filter.ts
backend/src/product/product.controller.ts
backend/src/product/product.module.ts
backend/src/product/product.service.ts

Resolves #51 
- 추적 상품 전체 목록 조회 요청이 오면, accessToken의 payload에 있는 userId를 통해 사용자가 추적하고 있는 상품에 대한 정보를 응답해준다.
- 상품 가격은 임시로 더미 데이터를 사용하였다.
- 기존 AuthExceptionFilter를 이름을 변경하여 재사용하였다.

사용자 추적 상품 전체 목록 조회 API 구현

---

backend/src/dto/product.add.dto.ts
backend/src/dto/product.dto.ts
backend/src/dto/product.swagger.dto.ts
backend/src/entities/product.entity.ts
backend/src/product/product.controller.ts
backend/src/product/product.module.ts
backend/src/product/product.repository.ts
backend/src/product/product.service.ts
backend/src/product/trackingProduct.repository.ts
backend/src/utils/openapi.11st.ts

Resolves #43 
**상품 추가 API 로직**
1. 상품 코드를 통해 상품테이블에 등록된 상품인지 DB에서 검색
2. 최초로 등록되는 상품이면 상품 테이블에 상품 추가
3. 이미 등록된 상품이면 상품 추가 X
4. 상품 추적 테이블에 사용자 ID, 상품 ID, 목표 가격을 저장
**변경 사항**
* `ProductDetailsDto`는 OpenAPI에서 상품 정보를 받아오기 위해 필요한 DTO인데, Product Table에 저장하기 위한 용도의 DTO도 필요하다고 생각해서 `ProductDto`를 별도로 만들어줬음.
* 따라서 기존에 있던 `ProductDto`는 `ProductAddDto`로 변경
* 11번가 Open API 호출 코드 함수로 분리
* 11번가 Open API에서 불러오는 가격 정보를 `Price`(원가)에서 `LowestPrice`(할인가)로 변경
* 기존에 사용하던 `Repository<TrackingProduct>`를 별도의 클래스 `TrackingProductRepository`로 분리

상품 추가 API 구현

---

backend/src/dto/product.add.dto.ts
backend/src/exceptions/exception.fillter.ts
backend/src/exceptions/validation.pipe.ts
backend/src/main.ts
backend/src/product/product.service.ts
backend/src/user/user.controller.ts

* 상품 추가 API, 상품 링크 검증 API에 유효하지 않은 값들이 들어올 때, 에러 발생
* 상품 API에서는 `HttpExceptionFilter`가 에러를 관리,
* `HttpExceptionFilter`에서 에러에 대한 response(400, 401, 404, 500 등)를 클라이언트에게 전달
**그러나 HttpException 타입이 아닌 에러는 HttpExceptionFilter에서 에러 발생**
`ex) error.getStatus() is not function`
* dto에 IsString, IsNumber, IsNotEmpty등과 같은 데코레이터 추가
* ~~try-catch문으로 타입이 맞지 않거나 빈 값일 경우`(ER_NO_DEFAULT_FOR_FIELD, ER_TRUNCATED_WRONG_VALUE_FOR_FIELD)`에 HttpException 생성~~
* 기존에 UserDTO 유효성 검사를 위해 사용하던 `UserValidationPipe`를 `GlobalValidationPipe`로 사용
* 모든 API 요청에 대해 유효성 검사를 하고 예외 처리를 할 수 있음.
* 최종적으로 `HttpExceptionFilter`에서 response를 정상적으로 전달

상품 API 내부 에러 핸들링 코드 작성

---

backend/src/dto/product.details.dto.ts
backend/src/dto/product.swagger.dto.ts
backend/src/entities/trackingProduct.entity.ts
backend/src/product/product.controller.ts
backend/src/product/product.service.ts
backend/src/product/trackingProduct.repository.ts

Resolves #3 
상품 추적 테이블과 상품 테이블을 left join하고 productId를 기준으로 그룹화 한 후,
사용자Id를 카운트 한 것을 기준으로 정렬하였다.
가격 정보는 더미 값을 사용하였다.

인기 상품 목록 API 구현

---

backend/src/product/trackingProduct.repository.ts

상품 인기 순위 섞이는 버그 수정

---

backend/src/auth/jwt/jwt.service.ts
backend/src/auth/jwt/jwt.strategy.ts
backend/src/constants.ts
backend/src/dto/auth.swagger.dto.ts
backend/src/dto/product.swagger.dto.ts
backend/src/dto/product.tracking.dto.ts
backend/src/dto/user.swagger.dto.ts
backend/src/product/product.controller.ts
backend/src/product/product.service.ts

Resolves #124
```
this.jwtRepository.saveToken(userId, '');
```
이전 버전의 refreshToken으로 접근할 경우 사용자의 최신 refreshToken을 비어있는 string으로 업데이트하여 최신 refreshToken까지 무효화하는 기능을 추가하였습니다.

최신 refreshToken 무효화,  상품 목록 API 응답 내용 수정, swagger 수정

---

backend/src/constants.ts
backend/src/dto/price.data.dto.ts
backend/src/dto/product.details.dto.ts
backend/src/product/product.controller.ts
backend/src/product/product.service.ts

- 상품의 상세정보를 담고 있는 cache를 구현하여,  서버에서 상품 정보를 얻기 위해 DB까지 접근할 필요가 없도록 하였습니다. cache에는  상품 id별로 상품의 최신가격, 최저가, 품절 여부를 저장하고 있습니다.
- 상품 가격 그래프를 그리기 위한 정보를 일 단위로 mongoDB에서 조회할 수 있도록 구현하였습니다. 상품 상세 정보는 현재 90일 단위로 조회 되고 있습니다.

상품 정보 cache 추가, 일정 기간 상품 정보 조회 추가

---

backend/package-lock.json
backend/package.json
backend/src/app.module.ts
backend/src/product/product.service.ts
backend/src/utils/openapi.11st.ts

주기적으로 상품 정보 조회 및 DB에 최신 정보 반영

---

backend/src/constants.ts
backend/src/dto/product.recommend.dto.ts
backend/src/dto/product.swagger.dto.ts
backend/src/product/product.service.ts
backend/src/product/trackingProduct.repository.ts

기존에 더미 데이터로 존재하던 최신 가격 정보를 cache 값을 활용하여 동기화했습니다.
동시에 기존에 목록들을 불러올 때, `Promise.all`을 사용하여 병렬로 처리되도록 개선하였습니다.
다만, `Promise.all`로 처리를 하면 단 하나의 Promise만 Reject되어도 전부 Reject 처리가 되는 문제가 있습니다.

추천/추적 상품 목록 조회 API에서 가격 그래프 데이터 및 최신 가격 정보 동기화

---

android/app/src/main/java/app/priceguard/ui/login/LoginViewModel.kt
android/app/src/main/java/app/priceguard/ui/signup/SignupActivity.kt
android/app/src/main/java/app/priceguard/ui/signup/SignupViewModel.kt
android/app/src/main/res/values/strings.xml

정규식
```
^(?=[A-Za-z\d!@#$%^&*()_+={};:'"~`,.?<>|\-\[\]\\/]*\d)(?=[A-Za-z\d!@#$%^&*()_+={};:'"~`,.?<>|\-\[\]\\/]*[a-z])(?=[A-Za-z\d!@#$%^&*()_+={};:'"~`,.?<>|\-\[\]\\/]*[A-Z])(?=[A-Za-z\d!@#$%^&*()_+={};:'"~`,.?<>|\-\[\]\\/]*[A-Za-z\d!@#$%^&*()_+={};:'"~`,.?<>|\-\[\]\\/])[A-Za-z\d!@#$%^&*()_+={};:'"~`,.?<>|\-\[\]\\/]{8,16}$
```

회원가입 이름 길이 제한, 비밀번호 정규식 수정

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/app/priceguard/ui/additem/AddItemActivity.kt
android/app/src/main/java/app/priceguard/ui/additem/link/RegisterItemLinkFragment.kt
android/app/src/main/java/app/priceguard/ui/additem/link/RegisterItemLinkViewModel.kt
android/app/src/main/java/app/priceguard/ui/additem/setprice/SetTargetPriceFragment.kt
android/app/src/main/java/app/priceguard/ui/detail/DetailActivity.kt

- Resolves #6 
https://github.com/boostcampwm2023/and09-PriceGuard/assets/83055885/94d29d1c-0f1f-4020-9fb1-3348d20ed0b6
링크가 아닌 그냥 텍스트도 공유가 되는데 intent filter에서는 구분이 불가능한 것 같습니다

다름 앱에서 공유 시 상품 추가 화면으로 이동

---

android/app/src/main/java/app/priceguard/data/GraphDataConverter.kt

일 그래프에서 이전 데이터가 잘리던 현상 수정
before
after

[버그] 일 그래프에서 이전 데이터가 잘리던 현상 수정

---

android/app/src/main/java/app/priceguard/ui/home/theme/ThemeDialogFragment.kt

- Resolves part of #197
왼쪽: 안드로이드 12 이하 디바이스
오른쪽: 안드로이드 14

다이나믹 테마 적용이 불가능한 OS면 다이나믹 테마 설정 View 비활성화

---

backend/src/cache/cache.service.ts
backend/src/cache/tracking.cache.ts
backend/src/constants.ts
backend/src/dto/product.add.dto.ts
backend/src/product/product.service.ts

상품 최초 등록시 Redis ttl 제거, tracking cache 순서 재구성 기능 누락 추가, targetPrice 최대값 설정

---

android/app/src/main/java/app/priceguard/ui/additem/setprice/SetTargetPriceFragment.kt
android/app/src/main/res/values/strings.xml

https://github.com/boostcampwm2023/and09-PriceGuard/assets/37584805/2e2037ae-36bf-4f75-b136-652f40093665

[상품 추가 화면] 가격 범위가 0~999999999 사이에서 설정되도록 수정

---

README.md

[README] 리드미 서브모듈 저장소 주소 추가

---

backend/src/product/product.service.ts

- Mongo에서 상품 가격을 조회할 때 일정 기간 내의 상품 가격을 조회하는데, 이 때 해당 기간 내에 부합하는 데이터가 없는 경우 서버 내부 로직에서 에러가 발생하였습니다.
- 따라서 해당 상품이 기간 내에 데이터가 없을 경우, 가장 최근 데이터를 다시 조회하도록 수정하였습니다.
- 사용자가 추적 중인 상품을 조회하였을 때, 특정 상품의 30일 내의 데이터가 Mongo에 존재하지 않아 조회 결과가 빈 배열이 반환되고 이후 서버 내부 로직 상에서 price 정보를 가져오려고 하니 에러가 발생한 로그 입니다.

상품 가격 조회 오류 수정

---

backend/src/constants.ts
backend/src/cron/cron.service.ts
backend/src/product/product.controller.ts
backend/src/product/product.service.ts
backend/src/utils/product.info.ts

-[x] 상품 조회 오류 수정 
-[x] 푸시 알림 shop 정보 추가 
-[x] URL 검증 api 분리
- cron 과정에서 변수 명이 불일치 하여 오류가 발생하는 이슈를 수정하였습니다.
-  푸시 알림에서도 11번가와 SmartStore를 구분하기 위해 shop 정보를 추가하였습니다.
-  URL 검증 과정에서 SmartStore를 지원하지 않는 어플에서 SmartStore 상품을 등록하는 경우, 11번가와 상품코드가 겹치면 잘 못 등록되는 오류가 있었습니다.
-  해당 문제로 인해 검증 URL도 버전을 분리하였습니다.

상품 조회 오류 수정, 푸시 알림 shop 정보 추가, URL 검증 api 분리

---

backend/src/cache/cache.service.ts
backend/src/cron/cron.service.ts

- 기존의 경우 상품 정보 갱신 시, 가격과 품절 여부만 갱신확인하였습니다
- 상품 이름과 이미지 URL이 변경되는 경우를 반영하기 위한 기능을 추가하였습니다.
- 위의 경우 추적 상품 캐시도 업데이트 되도록 하였습니다.
- 품절 상품의 경우, 가격이 목표 가격에 도달하여도 알림을 보내지 않도록 하였습니다.

상품 이름 및 이미지 갱신 추가, 품절 상품 알림 제외

---

.github/workflows/firebase-deploy.yml

Firebase App Distribution -> Play Store Automatic Export ([link](https://firebase.google.com/docs/app-distribution/android/distribute-console?apptype=aab))

Release 파일을 App Bundle 형식으로 변경

---

backend/src/auth/auth.controller.ts
backend/src/auth/auth.service.ts
backend/src/dto/user.dto.ts
backend/src/entities/user.entity.ts
backend/src/user/user.controller.ts
backend/src/user/user.repository.ts
backend/src/user/user.service.ts

- 사용자의 이메일이 인증되어 있는지 확인하는 API에 대하여 요청 방식을 accessToken으로 요청하도록 변경하였습니다.
- 회원 가입 API에 대하여, 기존 앱에 대한 회원 가입 기능을 유지하기 위해 API 버전을 분리하였습니다.
- 이메일로 전송된 인증 코드를 검증하는 경우, 사용자를 인증된 사용자로 판단하여 DB에 반영되도록 하였습니다.

이메일 인증 여부 API 요청 방식 변경, 회원 가입 API 버전 분리, 이메일 인증 DB 반영

---

backend/src/auth/auth.controller.ts
backend/src/dto/auth.swagger.dto.ts
backend/src/dto/user.swagger.dto.ts
backend/src/user/user.controller.ts

swagger 문서 수정

---

backend/src/mail/mail.verification.ejs

-  기존 이메일을 모바일에서 확인할 경우 공백 문자가 그대로 노출되는 문제가 있어 변경하였습니다.
[참고 자료](https://www.litmus.com/blog/the-little-known-preview-text-hack-you-may-want-to-use-in-every-email)
수정 전
수정 후

이메일 프리뷰 공백 문자 변경

---

.github/workflows/firebase-deploy.yml

v1.2.0 배포용 워크플로우 오류 수정 롤백

---

backend/src/configs/typeorm.config.ts

- DB 서버를 planetscale에서 OCI의 private subnet으로 이전함에 따라, planetscale에 연결하기 위해 필요했던 ssl 연결 설정을 제거하였습니다.

DB 서버 이전으로 이한 typeorm연결 설정 변경

---

backend/src/cron/cron.service.ts

- 기존에는 Promise.all로 인해 하나의 promise만 reject되더라도 모든 promise가 실패되었는데, 해당 현상을 개선하기 위해
Promise.allSettled를 이용하여 성공한 promise와 실패한 promise를 따로 처리할 수 있도록 변경하였습니다.

상품 정보 조회 promise 방식 변경
